version: '3.7'

services:
  streamlit-app:
    build:
      context: ./frontend
    container_name: streamlit_app
    expose:
      - "5000"

  cheshire-cat-vector-memory:
    image: qdrant/qdrant:v1.6.1
    container_name: cheshire_cat_vector_memory
    expose:
      - 6333
    volumes:
      - ./cat/long_term_memory/vector:/qdrant/storage
    restart: unless-stopped

  cheshire-cat-core:
    image: ghcr.io/cheshire-cat-ai/core:1.4.8
    container_name: cheshire_cat_core
    depends_on:
      - cheshire-cat-vector-memory
      - streamlit-app
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
      - CORE_HOST=${CORE_HOST:-localhost}
      - CORE_PORT=${CORE_PORT:-1865}
      - QDRANT_HOST=${QDRANT_HOST:-cheshire_cat_vector_memory}
      - QDRANT_PORT=${QDRANT_PORT:-6333}
      - CORE_USE_SECURE_PROTOCOLS=${CORE_USE_SECURE_PROTOCOLS:-}
      - API_KEY=${API_KEY:-}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-true}
      - SAVE_MEMORY_SNAPSHOTS=${SAVE_MEMORY_SNAPSHOTS:-false}
#    ports:
#      - ${CORE_PORT:-1865}:80
    expose:
      - "80"
    volumes:
      - ./cat/static:/app/cat/static
      - ./cat/plugins:/app/cat/plugins
      - ./cat/data:/app/cat/data
      - ./cat/embedder:/app/local_cache
    restart: unless-stopped